[package]
name = "chess"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[profile.release]
lto = true
strip = true
panic = "abort"
codegen-units = 1

[profile.release.build-override]
opt-level = 3

[dependencies]
anyhow = "1.0.95"

[build-dependencies]
anyhow = "1.0.95"
