[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chess-core = { path = "../core" }
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
crossbeam = "0.8.4"
