[package]
name = "chess-engine"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
strip = true
panic = "abort"
codegen-units = 1

[profile.release.build-override]
opt-level = 3

[dependencies]
chess-core = { path = "../chess-core" }
